version: '2.2'
services:
  hello:
    build:
      context: ./
      dockerfile: Dockerfile
    image: helloweb
    ports:
      - 8080
    networks:
      - network1
    scale: 3
networks:
  network1: